global_dist_boundary: 0.3
global_angle_boundary: 0.05 #0.05
HJ_MODE: 1  #0 Hanjeon, 1 docking postech, 
# 2 regular move postech
# HJ_MODE 2 +  Without_QR_move true : AMCL
# HJ_MODE 2+   Without_QR_move false: AMCL + QR number4 initialization
# HJ_MODE 3 for align
Without_QR_move: true
Main_start_x: 0.2 #0.5 #0.311524927616
Main_start_y:  0.0 #0 #-0.00846561
Main_goal_x: 2.0 #5 #2.33031272888
Main_goal_y: 0.1 #0.1 #-3.06516885757e-05
